#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SHORTCODES = ROOT / 'themes' / 'comichero' / 'layouts' / 'shortcodes'
OUT = ROOT / 'exampleSite' / 'content' / 'docs' / 'shortcodes-generated.md'

get_re = re.compile(r'\.Get\s+"([^"]+)"')

rows = []
for f in sorted(SHORTCODES.glob('*.html')):
    txt = f.read_text(encoding='utf-8', errors='ignore')
    params = sorted(set(get_re.findall(txt)))
    rows.append((f.stem, params))

lines = [
    '---',
    'title: "Shortcodes reference (generated)"',
    'date: 2026-05-05',
    'description: "Auto-generated shortcode parameter reference."',
    '---',
    '',
    '> This file is generated by `python scripts/generate_shortcode_docs.py`.',
    ''
]
for name, params in rows:
    lines.append(f'## `{name}`')
    if params:
        for p in params:
            lines.append(f'- `{p}`')
    else:
        lines.append('- _(no named params detected)_')
    lines.append('')

OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'generated: {OUT.relative_to(ROOT)}')
